luuuis/hass_wibeee

.travis.yml
README.md
custom_components/wibeee/manifest.json
hacs.json

Configures [Travis Releases Uploading](https://docs.travis-ci.com/user/deployment/releases/) and tells HACS to use releases instead of the main branch.

build: use releases in HACS

---

README.md
custom_components/wibeee/sensor.py

Read `scan_interval` from the sensor configuration, falling back to the 15 second default.

feat: add scan_interval support to allow this to be user-configured

---

custom_components/wibeee/sensor.py

Improves reliability when initialising the custom component and when updating the sensors after that.
- at start up, 10 retries
- after, 3 retries
There is a new `timeout` parameter to customise the request timeout if necessary.

fix: retry failed requests with exponential backoff

---

custom_components/wibeee/sensor.py

The component tries to update sensors even when they are disabled, triggering this warning.
```
2021-12-11 22:37:44 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.wibeee_xxxxxxxxxxxx_active_energy_l1 is incorrectly being triggered for updates while it is disabled. This is a bug in the wibeee integration
```
Under some conditions this also causes an exception within Home Assistant, causing the custom component to essentially "freeze" and stop updating all the other sensors as well.
```
2021-12-11 22:40:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/wibeee/sensor.py", line 257, in fetching_data
self.updating_sensors(sensor_data=fetched)
File …
```

fix: don't update entities that are disabled

---

README.md
custom_components/wibeee/sensor.py

In #13 we included the MAC address in the sensor name and that was then used by HA to derive the entity ID. This PR decouples the entity ID and name such that:
- the entity name is gotten from the "Device Name" configured in the Wibeee device web page, and
- the entity ID continues to be generated from the MAC address, e.g.: `sensor.wibeee_xxxxxxxxxxxx_active_energy_l1`
This gives us nice readable names out of the box while still providing unique entity ids for use in automations and also fixes the issue described in #17.

feat: use Wibeee device name to assign Home Assistant name

---

custom_components/wibeee/sensor.py

Stop updating `SensorEntity`'s `_attr_state` and `_attr_unit_of_measurement` properties as per https://developers.home-assistant.io/blog/2021/08/12/sensor_temperature_conversion/.
This fixes sensor updates in 2021.12 as seen in https://github.com/luuuis/hass_wibeee/discussions/17#discussioncomment-1858483.

chore: use _attr_native_value and _attr_native_unit_of_measurement

---

custom_components/wibeee/__init__.py
custom_components/wibeee/api.py
custom_components/wibeee/config_flow.py
custom_components/wibeee/const.py
custom_components/wibeee/manifest.json
custom_components/wibeee/sensor.py
custom_components/wibeee/translations/en.json

Adds a config flow to the integration as per [Integration Configuration](https://developers.home-assistant.io/docs/config_entries_config_flow_handler). This makes it easy to add and remove Wibeee devices without needing to go into YAML and without needing a restart.
Existing `platform: wibeee` YAML configuration is imported and ignored afterwards. Currently doesn't support overriding `scan_interval`.
Removes the `unique_id: false` option introduced in https://github.com/luuuis/hass_wibeee/pull/12 (only released in betas so far). Going forward all sensor and config entries will have a unique id.

feat: add config flow

---

custom_components/wibeee/__init__.py
custom_components/wibeee/config_flow.py
custom_components/wibeee/sensor.py
custom_components/wibeee/translations/en.json

Allows configuring the `scan_interval` as was previously possible using YAML. Also contains some minor tweaks to logging.

feat: add config flow options

---

custom_components/wibeee/api.py
custom_components/wibeee/config_flow.py
custom_components/wibeee/sensor.py
custom_components/wibeee/util.py

Adds `device_info` property to sensors so that they nest nicely within HA "devices":
- One device for the energy meter. The sensors containing the totals are under this device.
- One device for each of the 3 clamps. Holds the set of sensors for a single clamp.

feat: implement device info

---

custom_components/wibeee/api.py

This reduces the size of the logs and avoids scaring people with warnings that are handled by retries.

chore: set HTTP errors to DEBUG level when they are going to be retried

---

custom_components/wibeee/config_flow.py

The import flow was not properly aborting due to a bug in exception catching. Fixes https://github.com/luuuis/hass_wibeee/issues/28.

fix: abort import of configuration.yaml entry if already imported

---

custom_components/wibeee/config_flow.py
custom_components/wibeee/const.py
custom_components/wibeee/manifest.json
custom_components/wibeee/nest.py
custom_components/wibeee/sensor.py
custom_components/wibeee/translations/en.json

Adds a reverse HTTP proxy on port 8600 that fronts `http://nest-ingest.wibeee.com`. Pushed data is inspected and recorded in the HA state whenever possible.

feat: add nest proxy for Local Push support

---

custom_components/wibeee/sensor.py

Use `t` suffix instead of `4` in Local Push updates that pass through the Nest proxy. For example, `et` is used instead of `e4` for total active energy.
```
e1=11526830
e2=3331199
e3=4358096
et=19216125
```
Fixes #46.

fix: L4 local push updates are ignored

---

custom_components/wibeee/manifest.json

sort manifest keys per https://github.com/home-assistant/core/pull/87020

build: sort manifest keys as required by next HA versions

---

custom_components/wibeee/config_flow.py
custom_components/wibeee/translations/en.json

Allow HA to update a device's data when the device is already configured.

fix: update data when trying to add a device that's already configured

---

custom_components/wibeee/__init__.py
custom_components/wibeee/config_flow.py
custom_components/wibeee/const.py
custom_components/wibeee/nest.py
custom_components/wibeee/sensor.py
custom_components/wibeee/translations/en.json

Allows selecting a different Cloud service to upload. Also introduces Local-only mode for those who want to use Local Push without sending the data off to any Cloud service.
When running the new version for the first time the `ConfigEntry` is migrated to version 2 to support the new configuration select box.

Add configuration options to change the upstream URL

---

custom_components/wibeee/api.py
custom_components/wibeee/config_flow.py
custom_components/wibeee/sensor.py

Adds support for new undocumented API in 4.4.171. The old `status.xml` API seems to be no longer available.

feat(api): support values2.xml API used by firmware >= 4.4.171

---

custom_components/wibeee/sensor.py

Removed stray `device['macAddr']` reference that was inadvertently left behind when introducing new `DeviceInfo` class, which causes an error when setting up the integration.
```
Error while setting up wibeee platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/wibeee/sensor.py", line 247, in async_setup_entry
remove_push_listener = await async_setup_local_push(hass, entry, device, sensors)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/wibeee/sensor.py", line 195, in async_setup_local_push
mac_address = device['macAddr']
~~~~~~^^^^^^^^^^^
TypeError: tuple indices must be integers …
```

fix(nest): fixed local push not enabled

---

custom_components/wibeee/api.py
custom_components/wibeee/sensor.py
custom_components/wibeee/util.py

Wibeee's `values2.xml` API is returning WiFi secrets willy-nilly. Attempt to mask them out of log messages and returned dict to prevent downstream leakage.

fix(logging): mask values2.xml secrets

---

custom_components/wibeee/sensor.py

When there is an error polling the Wibeee device its respective sensors need to be marked as unavailable so that this gets accurately recorded in the History.
Fixes #74.

fix: mark sensors unavailable when polling fails

---

custom_components/wibeee/manifest.json
poetry.lock
pyproject.toml

Prior to 2024.2.0 we can't use lxml 5.x yet.
```
2024-02-14 09:45:25.793 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package lxml==5.1.0: ERROR: Cannot install lxml==5.1.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2024-02-14 09:45:35.037 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package lxml==5.1.0: ERROR: Cannot install lxml==5.1.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2024-02-14 09:45:43.460 ERROR (SyncWorker_3) …
```

chore: relax lxml requirement for compatibility with older HA

---

custom_components/wibeee/sensor.py

Recognise the `eacprodX` and `eacconsX` values that some device/firmware combinations are using (see #80).
```xml
<?xml version="1.0" encoding="UTF-8"?>
<values>
<variable>
<id>eac1</id>
<value>0</value>
</variable>
<variable>
<id>eacprod1</id>
<value>36514</value>
</variable>
<variable>
<id>eaccons1</id>
<value>28442</value>
</variable>
</values>
```

feat: add Active Energy Consumed/Produced sensors

---

custom_components/wibeee/sensor.py

Start using `UnitOfFrequency` and other unit enums. Fixes #96.

fix: remove usage of deprecated constants removed in 2025.1

---

custom_components/wibeee/nest.py
poetry.lock
pyproject.toml
tests/test_nest.py

Attempt to solve #99 by updating Nest Proxy responses in Local-only to emulate the responses returned by Nest Cloud.

fix: emulate Nest Cloud responses in Local-only mode

---

custom_components/wibeee/nest.py

`homeassistant.helpers.typing.EventType` is deprecated and will be removed soon in version 2025.5, see https://developers.home-assistant.io/blog/2024/04/08/deprecated-backports-and-typing-aliases/
Since the `EventType` is just an alias of `Event` ([source](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/typing.py)), it's safe to just replace one with the other.
This PR closes https://github.com/luuuis/hass_wibeee/issues/107

Migrate from deprecated homeassistant.helpers.typing.EventType to homeassistant.core.Event

---

custom_components/wibeee/__init__.py
tests/test_sensor.py

Fixes this error found while testing.
```
ERROR:homeassistant.config_entries:Error migrating entry Mock Title for wibeee
Traceback (most recent call last):
File "/Users/luis/Workspace/hass_wibeee/.venv/lib/python3.12/site-packages/homeassistant/config_entries.py", line 978, in async_migrate
result = await component.async_migrate_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/luis/Workspace/hass_wibeee/custom_components/wibeee/__init__.py", line 79, in async_migrate_entry
config_entry.version = 2
^^^^^^^^^^^^^^^^^^^^
File "/Users/luis/Workspace/hass_wibeee/.venv/lib/python3.12/site-packages/homeassistant/config_entries.py", line 463, in __setattr__
raise AttributeError(
AttributeError: version cannot be changed directly, use async_update_entry instead
```

fix: async_migrate_entry error when setting version

---

.github/workflows/release-please.yml
custom_components/wibeee/sensor.py
tests/test_sensor.py

Clears the following warning from logs.
```
WARNING  homeassistant.components.sensor:__init__.py:709 Entity sensor.wibeee_00_11_00_11_00_11_capacitive_reactive_energy_l1 (<class 'custom_components.wibeee.sensor.WibeeeSensor'>) is using native unit of measurement 'varh' which is not a valid unit for the device class ('energy') it is using; expected one of ['TWh', 'GJ', 'GWh', 'kcal', 'MWh', 'kJ', 'MJ', 'mWh', 'Mcal', 'Wh', 'kWh', 'Gcal', 'J', 'cal']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/luuuis/hass_wibeee/issues
WARNING  homeassistant.components.sensor:__init__.py:709 Entity sensor.wibeee_00_11_00_11_00_11_inductive_reactive_energy_l1 (<class 'custom_components.wibeee.sensor.WibeeeSensor'>) is using …
```

fix: don't use device_class=energy for sensors using varh as the unit

---

custom_components/wibeee/config_flow.py
custom_components/wibeee/const.py

Disable polling by default. Move towards Local Push-only, which is how Wibeee Nest works. This should help greatly with device stability.

feat: use Local-only mode by default (no polling)

---

.gitignore
README.md
config/configuration.yaml
custom_components/wibeee/sensor.py
docker-compose.yml
tests/test_sensor.py

Catching up to [July 10, 2022: Adopting a new way to name entities](https://developers.home-assistant.io/blog/2022/07/10/entity_naming/). Makes it easier to have entity ids and friendly names updated accordingly if the parent device is renamed.
⚠️ Entity ids are changed.

feat: update device and sensor names

---

custom_components/wibeee/__init__.py
custom_components/wibeee/config_flow.py
custom_components/wibeee/const.py
custom_components/wibeee/sensor.py
tests/test_sensor.py

Including these two pieces of information in the `ConfigEntry` allows us to create all sensors without having to use the device API, which is notoriously unstable.
Introduces an extra API call that is made when the `ConfigEntry` is upgraded in order to initially populate the data.
Added Docker files for local end-to-end testing.

chore: include MAC address and Wibeee ID in ConfigEntry

---

custom_components/wibeee/sensor.py

fix: missing state_class on _power_factor sensors

---

custom_components/wibeee/sensor.py

* sensors will now go unavailable instead of keeping their stale state
* only add sensors that are capable of receiving push updates, otherwise they would stay unavailable forever

feat: mark stale sensors unavailable if not receiving Local Push updates

---

custom_components/wibeee/nest.py
custom_components/wibeee/sensor.py
custom_components/wibeee/translations/en.json

Changes:
1. Show different "Repair" text depending on whether all or only some sensors are not updated 
2. Removed sensors that don't receive push updates.
3. Use `last_reported` instead of `last_updated`. The former is set even when the sensor values/attributes remain unchanged.
4. Set state threshold to 90s, re-check every 120s.

feat: several improvements around the "WIBEEE is not receiving updates" repair
